rd2.page("form2").addGroup("app").before(function(obj){
    
    rd2.form("form2").set({
        value1:{
            type:"text",
        },
        value2:{
            type:"text",
        },
        value2_0:{
            type:"text",
            style:"width:100px",
        },
        value3:{
            type:"text",
        },
        value3_0:{
            type:"text",
            style:"width:100px;display:inline-block",
        },
        value3_1:{
            type:"text",
            style:"width:100px;display:inline-block",
        },
        value4:{
            type:"text",
        },
        value4_0:{
            type:"text",
            style:"width:100px;display:inline-block",
        },
        value4_1:{
            type:"text",
            style:"width:100px;display:inline-block",
        },
        value5:{
            type:"text",
        },
        value5_0:{
            type:"text",
        },
        value6:{
            type:"text",
        },
        value7:{
            type:"text",
        },
        value8:{
            type:"text",
        },
        value9:{
            type:"text",
        },
        value10:{
            type:"text",
        },
        value11:{
            type:"text",
        },
        value12:{
            type:"text",
        },
        value13:{
            type:"text",
        },
        value14:{
            type:"text",
        },
        value15:{
            type:"text",
        },
        value16:{
            type:"text",
        },
        value17:{
            type:"text",
        },
        submit:{
            type:"submit",
            value:"Submit",
            styhle:"background:#4ac",
        },
    });

});