const rd2CallbackConst={
	redirectMode:{
		move:"move",
		back:"back",
	},
	base:{
		loading:"BASE_LOADING_",
	},
	page:{
		before:"PAGE_BEFORE_",
		after:"PAGE_AFTER_",
		leave:"PAGE_LEAVE_",
		beforeAll:"PAGE_BEFORE_All",
		afterAll:"PAGE_AFTER_All",
		leaveAll:"PAGE_LEAVE_All",
	},
	group:{
		before:"GROUP_BEFORE_",
		after:"GROUP_AFTER_",
		leave:"GROUP_LEAVE_",
	},
	form:{
		open:"FORM_OPEN_",
		submit:"FORM_SUBMIT_",
		reset:"FORM_RESET_",
		submitAll:"FORM_SUBMIT_ALL",
		resetAll:"FORM_RESET_ALL",
	},
};