rd2.page("form3").addGroup(["app"]).before(function(obj){
    
    rd2.form("form3").set({
		value1:{
			type:"checkbox",
			select:{
				0:"checkbox0",
				1:"checkbox1",
				2:"checkbox2",
				3:"checkbox3",
				4:"checkbox4",
				5:"checkbox5",
			},
		},
		value2:{
			type:"checkbox",
			select:{
				0:"checkbox0",
				1:"checkbox1",
				2:"checkbox2",
				3:"checkbox3",
				4:"checkbox4",
				5:"checkbox5",
			},
		},
		value3:{
			type:"checkbox",
			select:{
				0:"checkbox0",
				1:"checkbox1",
				2:"checkbox2",
				3:"checkbox3",
				4:"checkbox4",
				5:"checkbox5",
				6:"checkbox6",
				7:"checkbox7",
				8:"checkbox8",
				9:"checkbox9",
				10:"checkbox10",
				11:"checkbox11",
				12:"checkbox12",
				13:"checkbox13",
				14:"checkbox14",
			},
		},
		value4:{
			type:"checkbox",
			select:{
				0:"checkbox0",
				1:"checkbox1",
				2:"checkbox2",
				3:"checkbox3",
				4:"checkbox4",
				5:"checkbox5",
				6:"checkbox6",
				7:"checkbox7",
				8:"checkbox8",
				9:"checkbox9",
				10:"checkbox10",
				11:"checkbox11",
				12:"checkbox12",
				13:"checkbox13",
				14:"checkbox14",
			},
		},
		value5:{
			type:"text",
		},
		submit:{
			type:"submit",
			value:"Submit",
			style:"backgroudn:#4ac",
		}
	});
});